### ISSUE TITLE
The demos should have the same name

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/otbenchmark#17]
The following files should be renamed:

* https://github.com/JEBROUN/otbenchmark/blob/master/examples/RP53_Demonstration.ipynb: please rename it into RP53_Demo.ipynb
* https://github.com/JEBROUN/otbenchmark/blob/master/examples/RP8.ipynb: please rename it into RP8_demo.ipynb

**Comment by mbaudin47** [comment]
@JEBROUN : did you see the issue?

**Comment by mbaudin47** [comment]
@JEBROUN : could you please fix this file name issue?

**Comment by JEBROUN** [comment]
it is done!

**Comment by mbaudin47** [comment]
Cool: where?

**Comment by JEBROUN** [comment]
Indeed, I deleted the file RP53_Demonstration.ipynb, because the file RP53_Demonstration.ipynb and RP53_Demo.ipynb are the same.

I did that in the PR Example BBRC, but I see it now in the PR that you created !!!

**Comment by JEBROUN** [comment]
For RP8.ipynb, you can see it in the PR branch s10 that you created !!!

**Comment by JEBROUN** [comment]
![image](https://user-images.githubusercontent.com/43602056/82538312-da90da00-9b4b-11ea-8884-537eb5b03a0f.png)

**Comment by JEBROUN** [comment]
![image](https://user-images.githubusercontent.com/43602056/82538347-eaa8b980-9b4b-11ea-9744-f3ded59fc0c9.png)

**Comment by mbaudin47** [comment]
@JEBROUN what is the PR number ?

**Comment by JEBROUN** [comment]
In fact, I did that in the old PR ! I forgot his name!

**Comment by JEBROUN** [comment]
I think it was in #25

**Comment by mbaudin47** [comment]
Hence, the bug is fixed, which is why I close this ticket.
