### ISSUE TITLE
The Four branches Waarts system example is wrong

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/otbenchmark#30]
The Four branches Waarts system example is wrong:

https://github.com/mbaudin47/otbenchmark/blob/master/examples/four-branch-serial-system-Waarts.ipynb

* the file name is wrong: it should be FourBranchSerialSystemReliability-demo.ipynb
* it should use FourBranchSerialSystemReliability
* it does not plot the contours of the function, the limit state surface

**Comment by mbaudin47** [comment]
@JEBROUN : it this bug fixed?

**Comment by JEBROUN** [comment]
I did not make this change. I do it now

**Comment by mbaudin47** [comment]
Fixed at dea1005d5a4253fbadb64fd813ac7c7b06834d3a
