### ISSUE TITLE
ReliabilityProblem91 has bugs

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/otbenchmark#32]
There are bugs in the implementation of the RP91. The parameters of the gaussian distribution are wrongly implemented because mu1, sigma1 is used where it should not:

https://github.com/mbaudin47/otbenchmark/blob/7ca5d75e1f2b0232fa7885f3ac1bb3d21784050b/otbenchmark/ReliabilityProblem91.py#L101

https://github.com/mbaudin47/otbenchmark/blob/7ca5d75e1f2b0232fa7885f3ac1bb3d21784050b/otbenchmark/ReliabilityProblem91.py#L103

https://github.com/mbaudin47/otbenchmark/blob/7ca5d75e1f2b0232fa7885f3ac1bb3d21784050b/otbenchmark/ReliabilityProblem91.py#L105

**Comment by mbaudin47** [comment]
@JEBROUN : did you see this?

**Comment by JEBROUN** [comment]
This is my mistake, I solved this problem by a commit in PR " Example BBRC"

**Comment by mbaudin47** [comment]
Please insert the PR number with the format #XXX in the corresponding issue, so that we can see the link between the issue number and the PR number.

**Comment by mbaudin47** [comment]
@JEBROUN : please insert the PR number in a comment below.

**Comment by JEBROUN** [comment]
#25 !!

**Comment by mbaudin47** [comment]
The issue is fixed, this is why I close the issue.
