### ISSUE TITLE
There are two duplicate Notebooks

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/otbenchmark#36]
The two notebooks:

https://github.com/mbaudin47/otbenchmark/blob/master/examples/benchmark_2019.ipynb

and 

https://github.com/mbaudin47/otbenchmark/blob/master/examples/BBRC2019.ipynb

seems to be close duplicates.

This can be checked with:

https://nbviewer.jupyter.org/github/mbaudin47/otbenchmark/blob/master/examples/BBRC2019.ipynb
https://nbviewer.jupyter.org/github/mbaudin47/otbenchmark/blob/master/examples/benchmark_2019.ipynb

One of them should be removed.

**Comment by mbaudin47** [comment]
@JEBROUN : is this bug fixed?

**Comment by JEBROUN** [comment]
I made this change in the last PR : #37

**Comment by mbaudin47** [comment]
This issue was solved at #50, so I close it.
