### ISSUE TITLE
getDistribution() from a ReliabilityProblemXX() object

### ISSUE THREAD

**Issue by efekhari27** [mbaudin47/otbenchmark#43]
Hi @mbaudin47, 

I have had troubles getting the distribution of a reliability problem input distribution from a ReliabilityProblemXX() object.
Here is a very simple example the should reproduce this issue:

```
import openturns as ot
import otbenchmark as otb

rp_28 = otb.ReliabilityProblem28()
my_event = rp_28.getEvent()
my_dist = my_event.getDistribution()
print(my_dist)
```

This script raises the following error : 

```
RuntimeError: NotYetImplementedException : In RandomVectorImplementation::getDistribution() const

NOTE: the ThresholdEvent doesn't dispose of the getDistribution() method even if it is displayed on the ot documentation

```

There is probably a way that I don't see to reach the distribution. 
Thanks for your help, 

Elias
@vchabri @JEBROUN  FYI

**Comment by mbaudin47** [comment]
I think that what you are looking for is the antecedent:
```
inputVector = event.getAntecedent()
distribution = inputVector.getDistribution()
```
This is because there might be chains of events, composed with unions and interesections.

**Comment by mbaudin47** [comment]
Let me know if this works, so that I close the issue if fixed.

**Comment by efekhari27** [comment]
I just tried, it works perfectly. Thanks a lot for your quick answer.

**Comment by mbaudin47** [comment]
I do not think that this is possible. In order to create the same example with distribution arithmetic, you may use:
```
x1 = ot.Normal()
x2 = ot.Normal()
Y = x1 - x2 - 1.0
pf = Y.computeCDF(0.0)
```
There is no simple way to create the random variable Y based on the event. That is a pity, because this means that there is no way to automatically see which problems are solvable with computeCDF: we must handwrite the code.

**Comment by efekhari27** [comment]
Exactly the problem I faced when trying to apply ComputeCDF(0) to all the RP.
Thanks for your support, 
Elias

**Comment by mbaudin47** [comment]
Since there is no obvious solution, I close this issue.
