### ISSUE TITLE
There is no way to loop over the problems

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/otbenchmark#5]
There is no way to loop over the problems. Indeed, we would need a way to loop over the problems in the benchmark. 
A `ReliabilityProblemSet` class should be created. 
* The default constructor would provide an iterator over the problems in the set. 
* The example would show how to use it in a Monte-Carlo example.

**Comment by mbaudin47** [comment]
@JEBROUN: I think that you have a proposal on this topic, as you showed us a attempt to loop over the problems with several methods. Would you like to share it with a PR?

**Comment by JEBROUN** [comment]
ok, i share what i did

**Comment by mbaudin47** [comment]
Great. Let me know when you publish it and where.

**Comment by mbaudin47** [comment]
This issue is solved with PR#50, this is why I close it.
