### ISSUE TITLE
Can LogRelativeError be negative?

### ISSUE THREAD

**Issue by efekhari27** [mbaudin47/otbenchmark#86]
Hi Michaël, 

I was working around the following [example](https://github.com/mbaudin47/otbenchmark/blob/master/examples/reliability_benchmark_table.ipynb) and noticed something weird about the result formatting of the LogRelativeError. Cell 15, the LogRelativeError is formatted with an absolute value which I don't understand. 

Here is a simple example to illustrate my question: 
```
>>>import openturns as ot
>>>import otbenchmark as otb
>>>exact = 0.028
>>>apx1 = 0.022
>>>apx2 = 0.45
>>>print("Best log relative error (apx 1):", otb.ComputeLogRelativeError(exact, apx1))
>>>print("Worst log relative error (apx 2):", otb.ComputeLogRelativeError(exact, apx2))
Best log relative error (apx 1): 0.6690067809585754
Worst log relative error (apx 2): -1.1781544196194544
```
In this case, the approximation 2 (apx2) is very poor but by applying an absolute value to it, it would look like it's better than the approximation 1 (apx1). To me, the absolute value shouldn't be applied but I might be missing something.

Thanks your feedback, 
Best, 
Elias

**Comment by mbaudin47** [comment]
Hi Elias,
You are *absolutely* right :) : this is a mistake. 
The code:
```
"Correct Digits": lambda x: "{:.1f}".format(abs(x)),
```
could be replaced with:
```
"Correct Digits": lambda x: "{:.1f}".format(max(x, 0.0)),
```
so that a nonpositive real LRE is converted to zero. 
How many values are affected by this bug?

**Comment by mbaudin47** [comment]
Actually, it may happen that a negative floating point zero appear. In this case, the `max` function does not make it positive:
```
In [1]: x = -0.0

In [2]: x
Out[2]: -0.0

In [3]: max(x, 0.0)
Out[3]: -0.0
```

This is why the call to the `abs` function was useful. I fix the `ComputeLogRelativeError` as a better way to improve the printing of the results.
